ARG VPL_BASE_DISTRO=debian

FROM ${VPL_BASE_DISTRO}

USER root:root

COPY . /vpl-jail-system
WORKDIR /vpl-jail-system

RUN /vpl-jail-system/install-bash-sh

# Install levels: minimum < basic < standard < full
ARG VPL_INSTALL_LEVEL=basic
RUN /vpl-jail-system/install-vpl-sh noninteractive ${VPL_INSTALL_LEVEL}

# Using HTTP only
ENV VPL_JAIL_SECURE_PORT=0
EXPOSE 80

STOPSIGNAL SIGTERM

CMD ["/usr/sbin/vpl/vpl-jail-system", "start_foreground"]
