import time
import websocket
conn = websocket.create_connection('ws://localhost:8080')
print (str(conn.recv()))
time.sleep(0.1)
conn.send('hola')
time.sleep(0.1)
print (str(conn.recv()))
conn.send('close')
time.sleep(0.1)
print (str(conn.recv()))
conn.close()
conn = websocket.create_connection('ws://localhost:8080')
print (str(conn.recv()))
time.sleep(0.1)
conn.send('Adios')
time.sleep(0.1)
print (str(conn.recv()))
conn.send(b'texto en binario')
time.sleep(0.1)
print (conn.recv())
conn.send('end')
time.sleep(0.1)
print (str(conn.recv()))
conn.close()